### PR TITLE
Modify answer structrual testing

### PR DESCRIPTION
**Pull request by zhiyi-chen217**
I recognized that the answer for exercise 9 in structural testing is not consistent with the script. In the script introducing condition coverage, it discusses a combination of two conditions a > 10 && b > 20.  In this case, though && is a lazy operator, the test case T2 = (5, 30) is said to cover the cases of the first condition being false and the second condition being true. I also remember this is discussed in class and is explained as the lazy operator does not make a difference here.  However in the answer to exercise 9 it is explained differently. Therefore, I supposed the answer itself may be wrong and I tried to provide a correct version according to my understanding.

Best regards,
Zhiyi Chen

### CODE REVIEW

**Comment by mauricioaniche** [comment]
Hi, @zhiyi-chen217, the answer in the exercise is correct!

I think what you are missing is that, once a "return block" is reached, the program stops. So, for test case 1 (T1=15), the first if gets both conditions evaluated to true, and then the program returns _FizzBuzz_. So, for now we have:
* condition 1 = [true: exercised, false: not exercised]
* condition 2 = [true: exercised, false: not exercised]
* condition 3 = [true: not exercised, false: not exercised]
* condition 4 = [true: not exercised, false: not exercised]. At this moment, condition coverage = 2/8.

Then, T2 = 8. The first two conditions are evaluated to false. Then the third condition (`n%3==0`), false. Then the fourth condition, false. Then, the program returns "n!". So, for now we have: 
* condition 1 = [true: exercised, false: exercised]
* condition 2 = [true: exercised, false: exercised]
* condition 3 = [true: not exercised, false: exercised]
* condition 4 = [true: not exercised, false:  exercised]. 

At this moment, condition coverage = 6/8. (6 exercised / 8 total).

Did you get it?

**Comment by zhiyi-chen217** [comment]
Thank you so much for your response. However, the answer you've provided is just what I stated in my modified version. In the current version of the book, the answer is 5/8.

Best regards,
Zhiyi Chen

**Comment by zhiyi-chen217** [comment]
> Hi, @zhiyi-chen217, the answer in the exercise is correct!
> 
> I think what you are missing is that, once a "return block" is reached, the program stops. So, for test case 1 (T1=15), the first if gets both conditions evaluated to true, and then the program returns _FizzBuzz_. So, for now we have:
> 
> * condition 1 = [true: exercised, false: not exercised]
> * condition 2 = [true: exercised, false: not exercised]
> * condition 3 = [true: not exercised, false: not exercised]
> * condition 4 = [true: not exercised, false: not exercised]. At this moment, condition coverage = 2/8.
> 
> Then, T2 = 8. The first two conditions are evaluated to false. Then the third condition (`n%3==0`), false. Then the fourth condition, false. Then, the program returns "n!". So, for now we have:
> 
> * condition 1 = [true: exercised, false: exercised]
> * condition 2 = [true: exercised, false: exercised]
> * condition 3 = [true: not exercised, false: exercised]
> * condition 4 = [true: not exercised, false:  exercised].
> 
> At this moment, condition coverage = 6/8. (6 exercised / 8 total).
> 
> Did you get it?

Thank you so much for your response. However, the answer you've provided is just what I stated in my modified version. In the current version of the book, the answer is 5/8.

Best regards,
Zhiyi Chen

**Comment by mauricioaniche** [comment]
You are right, @zhiyi-chen217! I merged your answer and even added extra explanation there! Thanks!

**Pull request merged**
