### PR TITLE
Mistake in domain testing appendix

### PR DESCRIPTION
**Pull request by zhiyi-chen217**
I recognized that there is a little mistake in domain testing exercise 5. The on- and off-points for the boundary should be 36 and 35, instead of 37 and 35, since the score for ACT should be an integer from [0,36].

Best regards,
Zhiyi Chen

### CODE REVIEW

**Comment by mauricioaniche** [comment]
Hi, @zhiyi-chen217! The condition is `ACT=36`, so the two off points are 35 and 37. I think the answer is correct. 

Does that make sense?

**Comment by zhiyi-chen217** [comment]
> Hi, @zhiyi-chen217! The condition is `ACT=36`, so the two off points are 35 and 37. I think the answer is correct.
> 
> Does that make sense?

But in that column we are focusing on boundary analysis, shouldn't we find the on- and off-point, instead of two off-points?

Best regards,
Zhiyi Chen

**Comment by mauricioaniche** [comment]
Yes, we definitely need the _on-point_ (which is 36) and, in this case, the two _off-points_ of the equality (35 and 37). In this case, given that the partition itself already exercises the on point (there's no other value for ACT in that partition!), then, what's left for the boundary analysis are the off-points. Does that make sense?

For visualisation purposes, what you could have is three items in the boundary analysis column, for off=35, 37, and on=36. But then, when devising the tests, you would just create on test for the 36.

This is a tricky exercise, as the cascading conditions are really connected with each other. So, as a tester, you don't have a lot of flexibility in picking values for the test cases.

Let me know if that clears up your question!

**Comment by zhiyi-chen217** [comment]
> Yes, we definitely need the _on-point_ (which is 36) and, in this case, the two _off-points_ of the equality (35 and 37). In this case, given that the partition itself already exercises the on point (there's no other value for ACT in that partition!), then, what's left for the boundary analysis are the off-points. Does that make sense?
> 
> For visualisation purposes, what you could have is three items in the boundary analysis column, for off=35, 37, and on=36. But then, when devising the tests, you would just create on test for the 36.
> 
> This is a tricky exercise, as the cascading conditions are really connected with each other. So, as a tester, you don't have a lot of flexibility in picking values for the test cases.
> 
> Let me know if that clears up your question!

Thank you so much for your reply! So in this case we have two off-points and when testing the boundaries we can just choose one of them. As for the visualization purpose we can have all three cases in the table. Am I understanding correctly? 

I've made a new commit updating the table to have all three cases and I also find another typo in the text and that is corrected in the latest commit as well. Originally it is stated that with GPA 3.6, ACT 35, 37 would have the same result, which is not the case, since ACT 37 is an invalid input. I believe you mean ACT 35 and 36, since they all result in true with GPA 3.6.

I still have one question regarding the boundary analysis. Since {(36, 3.5), (37, 3.5)} and {(36, 3.5), (35, 3.5)}  represent boundaries for different classes(one for true -> invalid, the other for true -> false), is it necessary to have both off-points?

Best regards,
Zhiyi Chen

**Comment by mauricioaniche** [comment]
In case of an equality, you should test _both_ off-points!!! After all, there might be a bug in both sides! 

So:

- For an inequality, one test for the on-point, one test for the off-point, _always_
- For equalities, one test for the on-point, two tests for the two off-points, _always_

In the case of this exercise, we are testing all the boundaries (the one on-point and the two off-points) for all conditions. But because the rules in the requirement are so interconnected, you end up getting repeated tests (i.e., the same test exercises different boundaries).

I need to add more clarifications there, because this exercise is indeed tricky!

Maybe another way to solve it is: Analyse the partitions that emerge right out of the requirement:

* (= 36, >= 3.5)
* (>= 35, >= 3.6)
* (>= 34, >= 3.7)
* ...

To each of them, write a test with on-points. So, T1=(36,3.5), T2=(35, 3.6), T3=(34, 3.7).

Then, think of a test that exercises the "closest input that would fail that partition". So, for (>= 35, >= 3.6), we would have (35, 3.5), so 35 puts the student in, but 3.5 makes the student to be rejected, and (34, 3.6), now 3.6 puts the student in, but 34 makes him/her fail.

If you just repeat this to all the partitions, you will have all the boundary tests! 

What do you think?

Thanks for making me revisit this exercise. It's a theoretical one, but good to exercise the way of thinking!

**Comment by zhiyi-chen217** [comment]
> In case of an equality, you should test _both_ off-points!!! After all, there might be a bug in both sides!
> 
> So:
> 
> * For an inequality, one test for the on-point, one test for the off-point, _always_
> * For equalities, one test for the on-point, two tests for the two off-points, _always_
> 
> In the case of this exercise, we are testing all the boundaries (the one on-point and the two off-points) for all conditions. But because the rules in the requirement are so interconnected, you end up getting repeated tests (i.e., the same test exercises different boundaries).
> 
> I need to add more clarifications there, because this exercise is indeed tricky!
> 
> Maybe another way to solve it is: Analyse the partitions that emerge right out of the requirement:
> 
> * (= 36, >= 3.5)
> * (>= 35, >= 3.6)
> * (>= 34, >= 3.7)
> * ...
> 
> To each of them, write a test with on-points. So, T1=(36,3.5), T2=(35, 3.6), T3=(34, 3.7).
> 
> Then, think of a test that exercises the "closest input that would fail that partition". So, for (>= 35, >= 3.6), we would have (35, 3.5), so 35 puts the student in, but 3.5 makes the student to be rejected, and (34, 3.6), now 3.6 puts the student in, but 34 makes him/her fail.
> 
> If you just repeat this to all the partitions, you will have all the boundary tests!
> 
> What do you think?
> 
> Thanks for making me revisit this exercise. It's a theoretical one, but good to exercise the way of thinking!

Thank you for your explanation! I understand now! However, I recognized that the (37, 3.5) case is actually not listed in the final test suite, since it is invalid. Then shouldn't it be better if we change T15 to (37, 3.5) since it tests both the boundary and the invalid case for ACT being too large?

Best regards,
Zhiyi Chen

**Comment by mauricioaniche** [comment]
I’m happy you understood!

Changing T15 is definitely a good idea! We save a test and we better
exercise the boundary.

So, suggestion for this PR:

* Improve T15
* Write down this other way of solving the problem we discussed here (as it
seems easier to explain!) as a note just after the current answer

Deal?
-- 
--
Maurício Aniche
Delft University of Technology
http://www.mauricioaniche.com

**Comment by zhiyi-chen217** [comment]
> I’m happy you understood! Changing T15 is definitely a good idea! We save a test and we better exercise the boundary. So, suggestion for this PR: * Improve T15 * Write down this other way of solving the problem we discussed here (as it seems easier to explain!) as a note just after the current answer Deal? -- -- Maurício Aniche Delft University of Technology http://www.mauricioaniche.com

Thank you so much for your patience and help! I have added the note according to your explanation and modified T15 in the latest commit.

Best regareds,
Zhiyi Chen

**Pull request merged**
