### PR TITLE
Fixes in Static testing and Design for testability

### PR DESCRIPTION
**Pull request by drobiu**
- Fix indentation for bullet points in Implementation-level tips on designing for testability section of Design for testability
- Fix issue with regex expression rendering wrongly in Stating testing, fix strings accepted by the regex

### CODE REVIEW

**Comment by mauricioaniche** [comment]
@azqa Can you resolve this conflict? This PR is good, but the content of this line was changed in a previous commit, so I want to make sure we keep the improvements of both PRs!

**Comment by azqa** [comment]
@mauricioaniche I don't have write access on this repo. But the changes in the static-testing chapter are old, the current version is actually the correct one.

**Comment by mauricioaniche** [comment]
I just invited you to the repo!
-- 
--
Maurício Aniche
Delft University of Technology
http://www.mauricioaniche.com

**Comment by azqa** [comment]
Done. The static-testing part looks good now.

**Pull request merged**
